### ISSUE TITLE
Roadmap to Specification

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/ThorstensFirstApplication#1]
### Collaboration

- [ ] Read [Introduction to Git and GitHub](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/Introduction2Git/Introduction2Git.md)
- [ ] Read [Workflow for Contributing](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/WorkflowForContributing/WorkflowForContributing.md)
- [ ] Read [GitFlow Workflow](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/GitFlowWorkflow/GitFlowWorkflow.md)
- #002
- #003
- #004
- #005
- [ ] Make yourself familiar with the [Basic Syntax of Markdown](https://www.markdownguide.org/basic-syntax/)
- [ ] Read [Formulating Issues](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingIssues/FormulatingIssues.md)
- [ ] Read [Formulating Commit and Merge Request Messages](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingCommitMessages/FormulatingCommitMessages.md)
- [ ] Read [Management of Conflicts](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/ConflictManagement/ConflictManagement.md)
- [ ] Read [Avoiding Conflicts](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/AvoidingConflicts/AvoidingConflicts.md)
- #006

#### ServiceList

- [ ] Read [Structure of Services](./StructureOfServices/StructureOfServices.md)
- [ ] Read [Structure of ServiceNames](./StructureOfServiceNames/StructureOfServiceNames.md)
- [ ] Read [Structure of Release Numbers](./StructureOfReleaseNumbers/StructureOfReleaseNumbers.md)
- [ ] Read [Structure of UUIDs](./StructureOfUuids/StructureOfUuids.md) in general and for details about Servers and Clients
- [ ] Read [Concept of ServiceList](./ConceptOfServiceList/ConceptOfServiceList.md)
- [ ] #007

#### ProfileList

- [ ] Read [Concept of Profiles](./ConceptOfProfiles/ConceptOfProfiles.md)
- [ ] Read [Structure of UUIDs](./StructureOfUuids/StructureOfUuids.md) for details about Profiles
- [ ] Read [Concepts of ProfileList and ProfileInstanceList ](./ConceptOfProfileList/ConceptOfProfileList.md)
- [ ] #008
- [ ] #009
